from fastapi import APIRouter

from titanic.adapter.inbound.api.v1.crew_james_director_router import crew_james_director_router
from titanic.adapter.inbound.api.v1.crew_walter_roaster_router import crew_walter_roaster_router
from titanic.adapter.inbound.api.v1.crew_andrews_architect_router import crew_andrews_architect_router
from titanic.adapter.inbound.api.v1.passenger_cal_tester_router import passenger_cal_tester_router
from titanic.adapter.inbound.api.v1.crew_hartley_violin_router import crew_hartley_violin_router
from titanic.adapter.inbound.api.v1.passenger_isidor_couple_router import passenger_isidor_couple_router
from titanic.adapter.inbound.api.v1.passenger_jack_trainer_router import passenger_jack_trainer_router
from titanic.adapter.inbound.api.v1.passenger_rose_model_router import passenger_rose_model_router
from titanic.adapter.inbound.api.v1.passenger_ruth_survivor_router import passenger_ruth_survivor_router
from titanic.adapter.inbound.api.v1.crew_smith_captain_router import crew_smith_captain_router
from titanic.adapter.inbound.api.v1.crew_lowe_boat_router import crew_lowe_boat_router
from titanic.adapter.inbound.api.v1.passenger_molly_scaler_router import passenger_molly_scaler_router

titanic_router = APIRouter(prefix="/titanic", tags=["titanic"])
titanic_router.include_router(crew_james_director_router)
titanic_router.include_router(crew_walter_roaster_router)
titanic_router.include_router(crew_andrews_architect_router)
titanic_router.include_router(passenger_cal_tester_router)
titanic_router.include_router(crew_hartley_violin_router)
titanic_router.include_router(passenger_isidor_couple_router)
titanic_router.include_router(passenger_jack_trainer_router)
titanic_router.include_router(passenger_rose_model_router)
titanic_router.include_router(passenger_ruth_survivor_router)
titanic_router.include_router(crew_smith_captain_router)
titanic_router.include_router(crew_lowe_boat_router)
titanic_router.include_router(passenger_molly_scaler_router)

__all__ = ["titanic_router"]
