"""HOT 랭킹 출처 — MOVA_ERD `rankings.source`."""

RANKING_SOURCE_CHAT_TREND = "chat_trend"
RANKING_SOURCE_BOX_OFFICE = "box_office"
RANKING_SOURCE_MANUAL = "manual"

RANKING_SOURCES = frozenset(
    {
        RANKING_SOURCE_CHAT_TREND,
        RANKING_SOURCE_BOX_OFFICE,
        RANKING_SOURCE_MANUAL,
    },
)

DEFAULT_HOT_RANKING_SOURCE = RANKING_SOURCE_CHAT_TREND
